  <?php include('includes/connection.php');?>  

<!--header area-->
<?php include 'includes/header.php'; ?>

<!--sidebar area-->
<?php include 'includes/sidebar.php'; ?>

<?php


  $customer_name=$_SESSION['C_FNAME'];
  $email_id=$_SESSION['email'];
  $contact_no=$_SESSION['contact'];
  $amount=$_SESSION['mm']+150;;
  
  
include 'razorpay-php/Razorpay.php';
 //$apiKey = "rzp_test_YxfkUbFXwfG4Vc";
 use Razorpay\Api\Api;


$keyId = 'rzp_test_fDmVzWIk43LrqG';
$secretKey = '2vqsxsdMHHdMpVrmvQoP5x5h';
$api = new Api($keyId, $secretKey);




$paise=$amount*100;

$order= $api->order->create(array(
'receipt'=>rand(1000,9999).'ORD',
'amount'=>$paise,
'payment_capture'=>1,
'currency'=>'INR',)
);

?>
  <form role="form" method="post" action="transactionsave.php?action=adds">
<input type="hidden"  placeholder="HH-MM-AM/PM"  id="ftime" name="ftime" value="<?php echo date('Y-m-d') ?>"  class="form-control"/>
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard ? Settings ? API Keys
    data-amount="<?php echo $order->amount; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ?299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="HOMEOPATHY"
    data-description=""
    data-image="https://www.clipartmax.com/png/middle/356-3568187_justice-law-logo-template-vector.png"
    data-prefill.name="<?php echo $customer_name;  ?>"
	data-prefill.contact="<?php echo $contact_no;  ?>"
    data-prefill.email="<?php echo $email_id ?>"
    data-theme.color="#283179"
></script>

</form>